import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import HeaderNav from "@/components/header-nav";
import SubHeader from "@/components/sub-header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="light">
      <body className={inter.className}>
        <div className="min-h-screen w-full bg-gray-50">
          <HeaderNav />
          <SubHeader />
          {children}
        </div>
      </body>
    </html>
  );
}
